name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: set up secrets
      env:
        DEBUG_KEY_BASE64: ${{secrets.DEBUG_STORE_FILE}}
        RELEASE_KEY_BASE64: ${{secrets.RELEASE_STORE_FILE}}
        API_KEYS_BASE64: ${{secrets.API_KEY_PROPERTIES_FILE}}
        KEYSTORE_BASE64: ${{secrets.KEYSTORE_PROPERTIES_FILE}}
      run:  |
        echo $DEBUG_KEY_BASE64 | base64 --decode > debugkey.jks
        echo $RELEASE_KEY_BASE64 | base64 --decode > releasekey.jks
        echo $API_KEYS_BASE64 | base64 --decode > apikeys.properties
        echo $KEYSTORE_BASE64 | base64 --decode > keystore.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew buildDebug
